x-common-variables: &common-variables
    MONEYBIRD_AUTH_TOKEN: ${MONEYBIRD_AUTH_TOKEN}  
    MONEYBIRD_ADMINSTRATION_ID: ${MONEYBIRD_ADMINSTRATION_ID}

services:
  vscode:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    tty: true
    volumes:
      - ..:/tap-moneybird:cached
    environment:
      <<: *common-variables
