name: test-moneybird-tap
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-tap:
    runs-on: "ubuntu-latest"
    steps:
      # Copies the code from the respository to the runner
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installs poetry in the the runner [using the .venv of the project?]
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          # TODO: wat betekent dit precies?
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Configure poetry
        run: poetry install --no-interaction

      - name: Run pytests
        run: poetry run pytest meltano
        env:
          MONEYBIRD_AUTH_TOKEN: ${{MONEYBIRD_AUTH_TOKEN}}
          MONEYBIRD_ADMINSTRATION_ID: ${{MONEYBIRD_ADMINSTRATION_ID}}
